name: weekly_opportunity_finder

on:
  schedule:
    - cron: "0 8 * * 1"   # run every Monday at 8am UTC
  workflow_dispatch: {}    # allows manual run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run script
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
