name: weekly-opportunities

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch: {}

permissions:
  contents: read   # least privilege

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run script
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py

